#!/bin/bash

set -eux

source routing-release-ci/ci/scripts/script_helpers.sh

bosh_login_toolsmiths

bosh -d cf cloud-config > cloud-config.yml

# note: we are not operating on a bosh manifest
# just using "bosh interpolate" and "ops files"
# to edit a yml file automatically
OPS_FILE='routing-release-ci/ci/tasks/update-cloud-config-for-iso-seg-lbs/operation.yml'

bosh interpolate \
     cloud-config.yml \
     --ops-file="${OPS_FILE}" \
     > updated-cloud-config.yml

bosh update-cloud-config \
     updated-cloud-config.yml \
     --non-interactive
