#!/usr/bin/env bash

set -euo pipefail

PIPELINE_DIR="$(dirname $0)/pipelines"

PIPELINE_NAME=routing-toolsmiths

fly -t ga sync

fly \
  --target ga \
  set-pipeline \
  --pipeline "${PIPELINE_NAME}" \
  --config "${PIPELINE_DIR}/${PIPELINE_NAME}.yml"
